### ISSUE TITLE
When `kpt live` fails, show the last transition message(s) from the failing ready conditions

### ISSUE THREAD

**Issue by dflemstr** [GoogleContainerTools/kpt#582]
It would be useful to know why a `kpt live apply` fails.  Usually, the information in the ready conditions for the failing resources is sort of useful for that.  Something to consider!

## Current behavior

The command outputs something like:

```
error: timeout after 600 seconds waiting for 2 resources to reach condition AllCurrent
```

## Expected behavior

Something like:

```
error: timeout after 600 seconds waiting for 2 resources to reach condition AllCurrent:
bigtable-playground/my-bigtable-1: Update call failed: error applying desired state: Error creating instance. rpc error: code = AlreadyExists desc = Cannot re-create cluster 'gae-cluster-1' in a different instance
bigtable-playground/my-bigtable-2: Update call failed: error applying desired state: Error creating instance. rpc error: code = AlreadyExists desc = Cannot re-create cluster 'gae-cluster-2' in a different instance
```

**Comment by mortent** [comment]
I agree we could provide more information here. At the very least list the resources that failed to reconcile.

**Comment by mortent** [comment]
So this should be addressed by these two PRs:
https://github.com/kubernetes-sigs/cli-utils/pull/156
https://github.com/kubernetes-sigs/cli-utils/pull/166
It will be included in the next version of kpt.

Closing this issue, but feel free to repoen or file a new issue if this doesn't work as you expected.

**Comment by arnaud-mey** [comment]
I seem to still get the old behavior using kpt 0.31.0.

I'm seeing 
`Fatal error: timeout after 120 seconds waiting for 20 resources to reach condition AllCurrent` 
without more information on the resources that failed.

The full output: https://gist.github.com/arnaud-mey/d26569ec9feb44a1de8485fd12f4192a
